spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hk_db_test?characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


schedule:
  useSchedule: true
  useInit: true
  cron_for_api: "0 0 1 2 1 ?"


nager:
  holidays:
    url: https://date.nager.at/api/v3/PublicHolidays
  countries:
    url: https://date.nager.at/api/v3/AvailableCountries


custom:
  poolSize: 30
