server:
  port: 8090

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local
    include: secret
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


schedule:
  useSchedule: true
  useInit: true
  cron_for_api: "0 0 1 2 1 ?"

nager:
  holidays:
    url: https://date.nager.at/api/v3/PublicHolidays
  countries:
    url: https://date.nager.at/api/v3/AvailableCountries


logging:
  level:
    com.planit.holiday_keeper: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.springframework.transaction.interceptor: OFF
