spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hk_db?characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update


custom:
  poolSize: 100
