server:
  port: 8090
  shutdown: graceful

spring:
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/hd_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 172.17.0.1
      port: 6379
      password: ${custom.secret.spring.data.redis.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never


logging:
  level:
    com.planit.holiday_keeper: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO


schedule:
  useSchedule: true
  useInit: true
  cron_for_api: "0 0 1 2 1 ?"


nager:
  holidays:
    url: https://date.nager.at/api/v3/PublicHolidays
  countries:
    url: https://date.nager.at/api/v3/AvailableCountries


custom:
  poolSize: 4
